name: Demo Workflow

on:
  workflow_dispatch:
    inputs:
      environment:
        description: "Type 'prod' or 'nonprod'"
        required: true
        default: "prod"

jobs:
  demo-job:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Print environment
        run: echo "Environment selected: ${{ github.event.inputs.environment }}"

      - name: Say hello from master
        if: github.event.inputs.environment == 'prod'
        run: echo "Hello from master"

      - name: Say hello from test3
        if: github.event.inputs.environment == 'nonprod'
        run: echo "Hello from test3"
