name: Demo Workflow2

on:
  workflow_dispatch:

jobs:
  demo-job:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Run Hello World
        run: echo "Hello triggered manually2!"
      - name: Run Hello Actions
        run: echo "Hello Github actions2!"